using Data;
using Modelo;
using System;
using System.Collections.Generic;
using System.Text;

namespace Service
{
    public class EPCService
    {

        DataContext dataContext;

        public EPCService(DataContext context)
        {
            dataContext = context;
        }

        public List<EnfermedadesPreviasComorbilidades> GetEPC()
        {
            List<EnfermedadesPreviasComorbilidades> ListaDeECP = new List<EnfermedadesPreviasComorbilidades>();
            
            EnfermedadesPreviasComorbilidades EPC = new EnfermedadesPreviasComorbilidades();
            EPC.Asma = false;
            EPC.BajoPesoAlNacer = false;
            EPC.BronquitisPrevia = false;
            EPC.CantidadDePesoAlNacer = "521g";
            EPC.Diabetes = false;
            EPC.Embarzo = false;
            EPC.EnfermedadHepatica = false;
            EPC.EnfermedadNeurologica = false;
            EPC.EnfermedadOncologica = true;
            EPC.EnfermedadRenalCronica = true;
            EPC.EPOC = true;
            EPC.Fumador = false;
            EPC.HipertensionArterial = false;
            EPC.InmunoSupresionCongenitaOAdquirida = false;
            EPC.NAC_Previa = false;
            EPC.Obesidad = false;
            EPC.Prematuridad = false;
            EPC.Puerperio = false;
            EPC.PresentaEnfermedadesComorbilidades = true;
            EPC.SemanasDePrematuridad = "0";
            EPC.Tubercolosis = false;
            EPC.Otras = false;
            EPC.OtrasDetalle = "";
            ListaDeECP.Add(EPC);

            EnfermedadesPreviasComorbilidades EPC1 = new EnfermedadesPreviasComorbilidades();
            EPC1.Asma = false;
            EPC1.BajoPesoAlNacer = false;
            EPC1.BronquitisPrevia = false;
            EPC1.CantidadDePesoAlNacer = "480g";
            EPC1.Diabetes = false;
            EPC1.Embarzo = false;
            EPC1.EnfermedadHepatica = false;
            EPC1.EnfermedadNeurologica = false;
            EPC1.EnfermedadOncologica = false;
            EPC1.EnfermedadRenalCronica = false;
            EPC1.EPOC = false;
            EPC1.Fumador = false;
            EPC1.HipertensionArterial = false;
            EPC1.InmunoSupresionCongenitaOAdquirida = false;
            EPC1.NAC_Previa = false;
            EPC1.Obesidad = false;
            EPC1.Prematuridad = false;
            EPC1.Puerperio = false;
            EPC1.PresentaEnfermedadesComorbilidades = false;
            EPC1.SemanasDePrematuridad = "0";
            EPC1.Tubercolosis = false;
            EPC1.Otras = false;
            EPC1.OtrasDetalle = "";
            ListaDeECP.Add(EPC1);

            EnfermedadesPreviasComorbilidades EPC2 = new EnfermedadesPreviasComorbilidades();
            EPC2.Asma = true;
            EPC2.BajoPesoAlNacer = false;
            EPC2.BronquitisPrevia = false;
            EPC2.CantidadDePesoAlNacer = "425g";
            EPC2.Diabetes = false;
            EPC2.Embarzo = false;
            EPC2.EnfermedadHepatica = true;
            EPC2.EnfermedadNeurologica = true;
            EPC2.EnfermedadOncologica = false;
            EPC2.EnfermedadRenalCronica = false;
            EPC2.EPOC = false;
            EPC2.Fumador = true;
            EPC2.HipertensionArterial = false;
            EPC2.InmunoSupresionCongenitaOAdquirida = false;
            EPC2.NAC_Previa = false;
            EPC2.Obesidad = false;
            EPC2.Prematuridad = false;
            EPC2.Puerperio = false;
            EPC2.PresentaEnfermedadesComorbilidades = false;
            EPC2.SemanasDePrematuridad = "0";
            EPC2.Tubercolosis = false;
            EPC2.Otras = false;
            EPC2.OtrasDetalle = "";
            ListaDeECP.Add(EPC2);

            EnfermedadesPreviasComorbilidades EPC3 = new EnfermedadesPreviasComorbilidades();
            EPC3.Asma = false;
            EPC3.BajoPesoAlNacer = false;
            EPC3.BronquitisPrevia = false;
            EPC3.CantidadDePesoAlNacer = "650g";
            EPC3.Diabetes = true;
            EPC3.Embarzo = true;
            EPC3.EnfermedadHepatica = false;
            EPC3.EnfermedadNeurologica = false;
            EPC3.EnfermedadOncologica = false;
            EPC3.EnfermedadRenalCronica = false;
            EPC3.EPOC = false;
            EPC3.Fumador = false;
            EPC3.HipertensionArterial = false;
            EPC3.InmunoSupresionCongenitaOAdquirida = false;
            EPC3.NAC_Previa = false;
            EPC3.Obesidad = false;
            EPC3.Prematuridad = false;
            EPC3.Puerperio = false;
            EPC3.PresentaEnfermedadesComorbilidades = true;
            EPC3.SemanasDePrematuridad = "400g";
            EPC3.Tubercolosis = false;
            EPC3.Otras = false;
            EPC3.OtrasDetalle = "";
            ListaDeECP.Add(EPC3);

            EnfermedadesPreviasComorbilidades EPC4 = new EnfermedadesPreviasComorbilidades();
            EPC4.Asma = false;
            EPC4.BajoPesoAlNacer = false;
            EPC4.BronquitisPrevia = true;
            EPC4.CantidadDePesoAlNacer = "500g";
            EPC4.Diabetes = false;
            EPC4.Embarzo = false;
            EPC4.EnfermedadHepatica = false;
            EPC4.EnfermedadNeurologica = false;
            EPC4.EnfermedadOncologica = false;
            EPC4.EnfermedadRenalCronica = true;
            EPC4.EPOC = false;
            EPC4.Fumador = false;
            EPC4.HipertensionArterial = false;
            EPC4.InmunoSupresionCongenitaOAdquirida = false;
            EPC4.NAC_Previa = false;
            EPC4.Obesidad = false;
            EPC4.Prematuridad = false;
            EPC4.Puerperio = true;
            EPC4.PresentaEnfermedadesComorbilidades = false;
            EPC4.SemanasDePrematuridad = "0";
            EPC4.Tubercolosis = false;
            EPC4.Otras = false;
            EPC4.OtrasDetalle = "";
            ListaDeECP.Add(EPC4);

            EnfermedadesPreviasComorbilidades EPC5 = new EnfermedadesPreviasComorbilidades();
            EPC5.Asma = false;
            EPC5.BajoPesoAlNacer = false;
            EPC5.BronquitisPrevia = false;
            EPC5.CantidadDePesoAlNacer = "500g";
            EPC5.Diabetes = false;
            EPC5.Embarzo = false;
            EPC5.EnfermedadHepatica = true;
            EPC5.EnfermedadNeurologica = true;
            EPC5.EnfermedadOncologica = true;
            EPC5.EnfermedadRenalCronica = true;
            EPC5.EPOC = false;
            EPC5.Fumador = false;
            EPC5.HipertensionArterial = false;
            EPC5.InmunoSupresionCongenitaOAdquirida = false;
            EPC5.NAC_Previa = false;
            EPC5.Obesidad = false;
            EPC5.Prematuridad = false;
            EPC5.Puerperio = false;
            EPC5.PresentaEnfermedadesComorbilidades = false;
            EPC5.SemanasDePrematuridad = "0";
            EPC5.Tubercolosis = false;
            EPC5.Otras = false;
            EPC5.OtrasDetalle = "";
            ListaDeECP.Add(EPC5);

            EnfermedadesPreviasComorbilidades EPC6 = new EnfermedadesPreviasComorbilidades();
            EPC6.Asma = false;
            EPC6.BajoPesoAlNacer = false;
            EPC6.BronquitisPrevia = false;
            EPC6.CantidadDePesoAlNacer = "510g";
            EPC6.Diabetes = false;
            EPC6.Embarzo = false;
            EPC6.EnfermedadHepatica = false;
            EPC6.EnfermedadNeurologica = false;
            EPC6.EnfermedadOncologica = false;
            EPC6.EnfermedadRenalCronica = false;
            EPC6.EPOC = false;
            EPC6.Fumador = false;
            EPC6.HipertensionArterial = false;
            EPC6.InmunoSupresionCongenitaOAdquirida = true;
            EPC6.NAC_Previa = true;
            EPC6.Obesidad = true;
            EPC6.Prematuridad = false;
            EPC6.Puerperio = false;
            EPC6.PresentaEnfermedadesComorbilidades = false;
            EPC6.SemanasDePrematuridad = "0";
            EPC6.Tubercolosis = false;
            EPC6.Otras = false;
            EPC6.OtrasDetalle = "";
            ListaDeECP.Add(EPC6);

            EnfermedadesPreviasComorbilidades EPC7 = new EnfermedadesPreviasComorbilidades();
            EPC7.Asma = false;
            EPC7.BajoPesoAlNacer = false;
            EPC7.BronquitisPrevia = true;
            EPC7.CantidadDePesoAlNacer = "477g";
            EPC7.Diabetes = false;
            EPC7.Embarzo = false;
            EPC7.EnfermedadHepatica = false;
            EPC7.EnfermedadNeurologica = true;
            EPC7.EnfermedadOncologica = false;
            EPC7.EnfermedadRenalCronica = false;
            EPC7.EPOC = false;
            EPC7.Fumador = true;
            EPC7.HipertensionArterial = false;
            EPC7.InmunoSupresionCongenitaOAdquirida = false;
            EPC7.NAC_Previa = false;
            EPC7.Obesidad = false;
            EPC7.Prematuridad = false;
            EPC7.Puerperio = false;
            EPC7.PresentaEnfermedadesComorbilidades = false;
            EPC7.SemanasDePrematuridad = "0";
            EPC7.Tubercolosis = false;
            EPC7.Otras = false;
            EPC7.OtrasDetalle = "";
            ListaDeECP.Add(EPC7);

            EnfermedadesPreviasComorbilidades EPC8 = new EnfermedadesPreviasComorbilidades();
            EPC8.Asma = false;
            EPC8.BajoPesoAlNacer = false;
            EPC8.BronquitisPrevia = false;
            EPC8.CantidadDePesoAlNacer = "503g";
            EPC8.Diabetes = false;
            EPC8.Embarzo = false;
            EPC8.EnfermedadHepatica = false;
            EPC8.EnfermedadNeurologica = false;
            EPC8.EnfermedadOncologica = false;
            EPC8.EnfermedadRenalCronica = false;
            EPC8.EPOC = false;
            EPC8.Fumador = false;
            EPC8.HipertensionArterial = false;
            EPC8.InmunoSupresionCongenitaOAdquirida = false;
            EPC8.NAC_Previa = false;
            EPC8.Obesidad = false;
            EPC8.Prematuridad = false;
            EPC8.Puerperio = false;
            EPC8.PresentaEnfermedadesComorbilidades = true;
            EPC8.SemanasDePrematuridad = "8";
            EPC8.Tubercolosis = false;
            EPC8.Otras = false;
            EPC8.OtrasDetalle = "";
            ListaDeECP.Add(EPC8);

            EnfermedadesPreviasComorbilidades EPC9 = new EnfermedadesPreviasComorbilidades();
            EPC9.Asma = true;
            EPC9.BajoPesoAlNacer = false;
            EPC9.BronquitisPrevia = false;
            EPC9.CantidadDePesoAlNacer = "498g";
            EPC9.Diabetes = false;
            EPC9.Embarzo = false;
            EPC9.EnfermedadHepatica = false;
            EPC9.EnfermedadNeurologica = false;
            EPC9.EnfermedadOncologica = false;
            EPC9.EnfermedadRenalCronica = false;
            EPC9.EPOC = false;
            EPC9.Fumador = true;
            EPC9.HipertensionArterial = false;
            EPC9.InmunoSupresionCongenitaOAdquirida = false;
            EPC9.NAC_Previa = false;
            EPC9.Obesidad = false;
            EPC9.Prematuridad = false;
            EPC9.Puerperio = false;
            EPC9.PresentaEnfermedadesComorbilidades = false;
            EPC9.SemanasDePrematuridad = "0";
            EPC9.Tubercolosis = false;
            EPC9.Otras = false;
            EPC9.OtrasDetalle = "";
            ListaDeECP.Add(EPC9);

            //EnfermedadesPreviasComorbilidades EPC10 = new EnfermedadesPreviasComorbilidades();
            //EPC10.Asma = false;
            //EPC10.BajoPesoAlNacer = false;
            //EPC10.BronquitisPrevia = false;
            //EPC10.CantidadDePesoAlNacer = "459g";
            //EPC10.Diabetes = true;
            //EPC10.Embarzo = false;
            //EPC10.EnfermedadHepatica = false;
            //EPC10.EnfermedadNeurologica = false;
            //EPC10.EnfermedadOncologica = false;
            //EPC10.EnfermedadRenalCronica = false;
            //EPC10.EPOC = false;
            //EPC10.Fumador = false;
            //EPC10.HipertensionArterial = false;
            //EPC10.InmunoSupresionCongenitaOAdquirida = false;
            //EPC10.NAC_Previa = false;
            //EPC10.Obesidad = false;
            //EPC10.Prematuridad = false;
            //EPC10.Puerperio = false;
            //EPC10.PresentaEnfermedadesComorbilidades = false;
            //EPC10.SemanasDePrematuridad = "350g";
            //EPC10.Tubercolosis = false;
            //EPC10.Otras = false;
            //EPC10.OtrasDetalle = "";
            //ListaDeECP.Add(EPC10);

            return ListaDeECP;
        }
    }
}
